version: '3.4'

services:
  dutchazuremeetup.webapi:
    image: ${DOCKER_REGISTRY-}dutchazuremeetupwebapi${TAG}
    build:
      context: .
      dockerfile: DutchAzureMeetup.WebApi/Dockerfile

  dutchazuremeetup.webapp:
    image: ${DOCKER_REGISTRY-}dutchazuremeetupwebapp${TAG}
    build:
      context: .
      dockerfile: DutchAzureMeetup.WebApp/Dockerfile

